name: Node CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your source code
      - name: Check out repo
        uses: actions/checkout@v4

      # 2) Set up Node.js (pick the version you want to use)
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) Install dependencies
      - name: Install dependencies
        run: npm install

      # 4) (Optional) Build or run your server
      # If you have a build script in package.json:
      - name: Build the app (optional)
        run: npm run build --if-present

      # 5) Run tests, or just run the server
      #- name: Run tests
      #  run: npm test
