name: Energy Measurement Test

on: [push]

jobs:
  test-energy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Monitoring Tools
        run: sudo apt update && sudo apt install -y time

      - name: Run Test Script with Timing
        run: |
          echo "Running workload..."
          /usr/bin/time -v bash -c "for i in {1..1000000}; do :; done"

      - name: Capture System Metrics
        run: |
          echo "CPU Information:"
          lscpu
          echo "Memory Usage:"
          free -h
